Potter kata
tunavla/PotterKata pull request #2
Opened 2022-08-22 22:20 UTC by tunavla

2022-08-23 08:59 UTC, rbsgn requested changes

2022-08-23 08:59 UTC, rbsgn commented on Tests/PotterKataTests/PotterKataTests.swift
> +        assertPrice(for: books, expectedPrice: result)
Код, признаюсь, сложный. До конца не переварил, но взгляд зацепился за несоответствие. В комментарии к этому методу написано, что для этих данных цена должна быть 60.8$, а `8 * 5 * 0.75 + 8 * 5 * 0.75` равно `60$`.

2022-08-23 09:35 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +        count: Constants.librarySize * 2.pow(Constants.librarySize))
Почему цен так много? Почему именно 2^7 штук?

2022-08-23 09:35 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +        let key = getPriceKey(library: library)
Что такое _ключ_ и почему он так вычисляется?

2022-08-23 09:35 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +        var (libraries1, libraries2) = splitLibrary(library)
Вот тут, наверное, самая мякотка: Для чего нужно разделение? Как вообще устроен алгоритм?

2022-08-23 09:35 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +        !library.contains { $0 > 1 }
Вот тут тоже не улавливаю логику: Почему возможность покупки — это количество книг больше 1?

2022-08-23 09:35 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +            if book == 1 { count += 1 }
Почему `count` увеличивается только если книг 1?

2022-08-23 09:35 UTC, rbsgn commented on Tests/PotterKataTests/PotterKataTests.swift
> +        assertPrice(for: books, expectedPrice: result)
Обсудили в личке. Выяснилось, что это если вычислять «в лоб», то получится 60.8$, а должно быть 60$.

2022-08-23 10:07 UTC, tunavla commented on Tests/PotterKataTests/PotterKataTests.swift
> +        assertPrice(for: books, expectedPrice: result)
перепишу комментарий, чтобы он не сбивал

2022-08-23 10:54 UTC, tunavla commented on Sources/PotterKata/PotterBookStore.swift
> +        var (libraries1, libraries2) = splitLibrary(library)
основное условия задачи: скидка применяется только на ту последовательность, в которой нет повторение книг

чтобы найти оптимальную цену, нам нужно пройтись по всем комбинациям и найти наименьшую по цене

можно сделать вывод, что это решение в лоб, но решение в лоб было возвращать самую длинную последовательность уникальных книг, так как скидка зависит от количества уникальных книг

но этот вариант не всегда возвращает наименьшую цену(последний тест кейс), поэтому нам надо проходить по всем возможным последовательностям и сравнивать

разделение нужно как раз таки, чтобы получить и посчитать разные последовательности книг
оно рекурсивное,  таким образом мы проходимся прям по всем

так же мы утверждаем, что достаточно каждый раз разбивать именно на 2 части (А и Б пусть), а не на 3 (А, Б и В, т.к. при последующем рекурсивном разбиении мы всё равно получим эту В

2022-08-23 10:54 UTC, tunavla commented on Sources/PotterKata/PotterBookStore.swift
> +        !library.contains { $0 > 1 }
спасибо, что подсветил проблему с названием метода

это больше про возможность применение скидки
то есть есть условие - чтобы в последовательности были только разные книги, если будет повтор, то скидка не применится 
**в library мы храним количество книг, где index - id книги**
и это проверка - возможно ли к этому набору книг(к library) применить скидку

2022-08-23 10:54 UTC, tunavla commented on Sources/PotterKata/PotterBookStore.swift
> +            if book == 1 { count += 1 }
мы ранее отфильтровали последовательности, и теперь у нас в library только 0 и 1
мы считаем только количество добавленных книг, поэтому и смотрит на 1, в принципе запросто можно заменить на != 0

2022-08-23 11:22 UTC, tunavla commented on Sources/PotterKata/PotterBookStore.swift
> +        let key = getPriceKey(library: library)
> Что такое ключ

Ключ - это  уникальный индекс в массиве цен


> Почему он так вычисляется

один из вариантов получения уникального значения
вычисляется как a_i * 2^i
нагляднее видно в примерах:
[0 0 1 2] = 0 * 2^0 + 0 * 2^1 + 1 * 2^2 +  2 * 2^3 = 0 + 0 + 4 + 16 = 20
[0 2 3] = 0 * 2^0 + 2 * 2^1 + 3 * 2^2 = 0 + 4 + 12 = 16
так как вариантов книг всего 8
то и последовательность книг - массив из 8 элементов, то есть максимальная степень 2 - 7

2022-08-23 11:22 UTC, tunavla commented on Sources/PotterKata/PotterBookStore.swift
> +        count: Constants.librarySize * 2.pow(Constants.librarySize))
этот массив существует для того, чтобы не пересчитывать цену последовательности, которую мы уже до этого вычислили
чуть ниже я описала вычисление ключа
ключ - индекс в этом массиве
размер массива == максимальное значение ключа

2022-08-25 13:21 UTC, rbsgn reviewed
Задание зачитываю

2022-08-25 13:21 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +        !library.contains { $0 > 1 }
Окей, тогда жду переименование метода.

2022-08-25 13:21 UTC, rbsgn commented on Sources/PotterKata/PotterBookStore.swift
> +            if book == 1 { count += 1 }
Окей, тогда действительно лучше заменить на `!= 0` и переименовать `count` во что-то в духе _количество книг, учитывающееся в скидке_.

2022-08-31 11:00 UTC, tunavla commented
переименовала, как ты и просил)

2022-09-02 16:47 UTC, merged